const courses = [
    { number: 'Course 001', title: '最初の通信', summary: '出力・文字列・引用符・エラーの読み方を、予測とデバッグを通じて身につけます。', skill: 'print / 文字列', xp: 120, lessons: [
            { type: 'story', title: 'なぜ出力が必要？', subtitle: '必要性を理解', headline: '見えない状態を、外へ伝える。', body: '宇宙船のエンジンは動いているはずですが、内部の状態が画面に何も出ません。プログラムの中で起きたことを確認するには、外へ情報を出力する必要があります。', concept: 'Pythonでは print(...) を使って、文字や値を画面に表示します。これは学習用だけでなく、実務で状態確認やデバッグをするときにも使う基本動作です。', diagram: ['print("起動")', 'Pythonが命令を実行', '起動'], question: 'この場面で print が必要な理由として最も適切なのは？', choices: ['プログラムを終了するため', '内部の状態を画面で確認するため', '文字を削除するため'], answer: 1, explain: 'printは、プログラム内部の値や状態を外から確認する手段です。' },
            { type: 'predict', title: '実行前に予測', subtitle: '結果を考える', headline: 'コードを読む力を育てる。', body: '実行ボタンを押す前に、何が表示されるか予測してください。', code: 'print("通信開始")', question: '実行結果はどれ？', choices: ['print', '通信開始', '"通信開始"'], answer: 1, explain: '引用符は文字列の境界を示す記号で、画面には中身だけが表示されます。' },
            { type: 'code', mode: 'edit', title: '文字列を書き換える', subtitle: '小さく成功', headline: '自分の通信メッセージを送る。', body: '「ゲスト」をあなたの好きな名前へ書き換えて実行してください。', starter: 'print("ゲスト")', goal: 'ゲスト以外の文字列を表示する', hint: '引用符の内側だけを書き換えます。例: print("Hikari")', tests: ['printを使っている', '引用符で文字列を囲んでいる', 'ゲスト以外を出力している'] },
            { type: 'debug', title: '壊れた通信を直す', subtitle: 'エラーを読む', headline: 'SyntaxErrorを怖がらない。', body: '閉じる引用符が欠けています。エラーの場所を見つけて修正してください。', starter: 'print("SOS)', goal: 'SOS と表示する', hint: '開始したダブルクォーテーションには、対応する終了記号が必要です。', tests: ['引用符が左右そろっている', '括弧が閉じている', 'SOSを出力する'] },
            { type: 'code', mode: 'free', title: 'ゼロから書く', subtitle: '再現する', headline: '何もない場所から命令を書く。', body: '空のエディタに、Pythonで「エンジン正常」と表示するコードを書いてください。', starter: '', goal: 'エンジン正常 と表示する', hint: 'print("表示したい文字") の形を使います。', tests: ['printを使っている', 'エンジン正常を文字列にしている', '正しい出力になる'] },
            { type: 'transfer', title: '別の場面へ応用', subtitle: '転移を確認', headline: '同じ知識を別の目的で使う。', body: '警告ログとして「燃料残量 20%」を表示してください。学んだ形は同じですが、目的と文脈が変わっています。', starter: '# ここに警告ログを書く', goal: '燃料残量 20% と表示する', hint: 'コメント行の下にprintを追加します。', tests: ['コメントを残している', 'printを使っている', '燃料残量 20%を出力する'] },
            { type: 'boss', title: 'ボス：救難信号', subtitle: '総合問題', headline: '3行の通信を完成させる。', body: '次の3行を順番に表示してください。「通信接続」「こちら探査船」「救援を要請します」', starter: '# 3行の救難信号を送信しよう\n', goal: '指定された3行を順番に表示する', hint: 'printを3回使う方法が最も簡単です。', tests: ['printを3回以上使っている', '3つの文章がすべて含まれる', '指定順で3行出力される'], world: true }
        ] },
    { number: 'Course 002', title: '記憶装置「変数」', summary: '値に名前を付けて保存し、変更し、再利用する意味を理解します。', skill: '変数 / 代入', xp: 150, lessons: [
            { type: 'story', title: 'なぜ変数が必要？', subtitle: '重複を減らす', headline: '値に名前を付けて覚えさせる。', body: '船名を何度も直接書くと、名前を変えるたびにすべて修正する必要があります。値へ名前を付けて一か所で管理する仕組みが変数です。', concept: 'name = "Aurora" のように書くと、文字列を name という変数に保存できます。以降はnameを使って同じ値を再利用できます。', diagram: ['name = "Aurora"', 'name に値を保存', 'print(name) → Aurora'], question: '変数を使う主な利点は？', choices: ['値を保存し、再利用・変更しやすくする', '必ず計算を速くする', 'エラーを完全になくす'], answer: 0, explain: '変数は値に名前を付け、意味を持たせながら再利用しやすくします。' },
            { type: 'predict', title: '値を追跡する', subtitle: '代入を読む', headline: '最後に入った値を予測する。', body: '変数は後から新しい値へ更新できます。', code: 'fuel = 80\nfuel = 65\nprint(fuel)', question: '何が表示される？', choices: ['80', '65', 'fuel'], answer: 1, explain: '2行目でfuelの中身が65へ更新されるため、最後は65です。' },
            { type: 'code', mode: 'edit', title: '船名を保存する', subtitle: '代入を書く', headline: '文字列を変数へ格納する。', body: 'ship_nameに「Nova」を保存し、その変数をprintで表示してください。', starter: 'ship_name = "ゲスト船"\nprint(ship_name)', goal: 'Nova と表示する', hint: '1行目の引用符の中身をNovaへ変更します。', tests: ['ship_nameへ代入している', 'printで変数を使っている', 'Novaを出力する'] },
            { type: 'debug', title: '変数名のミスを直す', subtitle: 'NameError', headline: '似た名前の違いを見抜く。', body: '保存した変数名と表示時の変数名が一致していません。修正してください。', starter: 'pilot_name = "Mira"\nprint(pilot)', goal: 'Mira と表示する', hint: 'Pythonではpilot_nameとpilotは別の名前です。', tests: ['代入した変数名を使っている', 'NameErrorが起きない', 'Miraを出力する'] },
            { type: 'code', mode: 'free', title: '数値を保存する', subtitle: '型の違い', headline: '燃料残量を数値として持つ。', body: 'fuelという変数へ80を保存し、print(fuel)で表示してください。数値には引用符を付けません。', starter: '', goal: '80 と表示する', hint: 'fuel = 80 の次の行でprint(fuel)を書きます。', tests: ['fuelへ数値を代入している', '引用符なしの80を使っている', '80を出力する'] },
            { type: 'transfer', title: '値を更新する', subtitle: '状態変化', headline: '消費後の燃料を表現する。', body: 'fuelを100で開始し、その後75へ更新して、最後の値を表示してください。', starter: 'fuel = 100\n# 燃料を75へ更新\n', goal: '75 と表示する', hint: 'fuel = 75 と再代入した後にprint(fuel)を使います。', tests: ['fuelを100で初期化している', 'fuelを75へ更新している', '最後に75を出力する'] },
            { type: 'boss', title: 'ボス：船体ステータス', subtitle: '複数変数', headline: '3つの状態を管理する。', body: 'ship="Orion"、fuel=72、crew=4を変数へ保存し、3つを順番に表示してください。', starter: '# 船体ステータスを変数で管理しよう\n', goal: 'Orion、72、4を順番に表示する', hint: '3つの代入と3つのprintを使います。', tests: ['3つの変数へ正しく代入している', '変数をprintしている', 'Orion・72・4を順番に出力する'], world: true }
        ] },
    { number: 'Course 003', title: '分岐する航路', summary: '条件によって動作を変えるif文を、予測・デバッグ・総合判断で学びます。', skill: 'if / 条件分岐', xp: 180, lessons: [
            { type: 'story', title: 'なぜ分岐が必要？', subtitle: '状況に応じる', headline: '同じ動作では危険を避けられない。', body: '燃料が十分なときと不足しているときで、宇宙船は異なる行動を取る必要があります。条件に応じて処理を選ぶのがif文です。', concept: 'if 条件: の下にインデントした処理を書くと、条件がTrueのときだけ実行されます。', diagram: ['if fuel < 20:', '条件が真か判定', '警告を表示'], question: 'if文の役割は？', choices: ['必ず同じ処理を繰り返す', '条件に応じて実行内容を変える', '変数を削除する'], answer: 1, explain: 'ifは条件を評価し、真の場合だけ指定処理を実行します。' },
            { type: 'predict', title: '条件を評価する', subtitle: 'True/False', headline: '比較結果を予測する。', body: 'fuelは15です。条件 fuel < 20 は真になります。', code: 'fuel = 15\nif fuel < 20:\n    print("警告")', question: '何が表示される？', choices: ['何も表示されない', '警告', '15'], answer: 1, explain: '15は20より小さいため条件がTrueになり、printが実行されます。' },
            { type: 'code', mode: 'edit', title: '警告条件を作る', subtitle: '比較を書く', headline: '燃料が少ないときだけ知らせる。', body: 'fuel=10のとき「補給が必要」と表示されるよう、条件の数値を書き換えてください。', starter: 'fuel = 10\nif fuel < 5:\n    print("補給が必要")', goal: '補給が必要 と表示する', hint: '10より大きいしきい値にします。例えば20です。', tests: ['if文を使っている', 'fuelが条件を満たす', '補給が必要を出力する'] },
            { type: 'debug', title: 'インデントを直す', subtitle: 'IndentationError', headline: '処理のまとまりを空白で示す。', body: 'ifの次の行にインデントがありません。printの前へ4つの空白を入れてください。', starter: 'fuel = 5\nif fuel < 10:\nprint("緊急補給")', goal: '緊急補給 と表示する', hint: 'printの前に半角スペース4つを入れます。', tests: ['ifの行がコロンで終わる', 'printがインデントされている', '緊急補給を出力する'] },
            { type: 'code', mode: 'free', title: '安全判定を書く', subtitle: 'ゼロから分岐', headline: '酸素量を確認する。', body: 'oxygen=30を保存し、oxygen < 40のとき「酸素不足」と表示するif文を書いてください。', starter: '', goal: '酸素不足 と表示する', hint: '代入、if条件、インデントしたprintの3行です。', tests: ['oxygenを30にしている', 'oxygen < 40を判定している', '酸素不足を出力する'] },
            { type: 'transfer', title: 'elseで二つの結果', subtitle: '二者択一', headline: '安全と危険の両方を扱う。', body: 'temperature=18です。20以上なら「適温」、それ以外なら「低温」と表示してください。', starter: 'temperature = 18\n# if / else を追加\n', goal: '低温 と表示する', hint: 'if temperature >= 20: の後にelse:を使います。', tests: ['ifとelseを使っている', '20以上を条件にしている', '18のとき低温を出力する'] },
            { type: 'boss', title: 'ボス：着陸判断AI', subtitle: '総合分岐', headline: '燃料と天候から決断する。', body: 'fuel=35、weather="clear"です。fuelが30以上 かつ weatherがclearなら「着陸許可」、それ以外なら「待機」と表示してください。', starter: 'fuel = 35\nweather = "clear"\n# 着陸判断を書く\n', goal: '着陸許可 と表示する', hint: '条件は if fuel >= 30 and weather == "clear": です。', tests: ['andで2条件を組み合わせている', 'ifとelseを使っている', '着陸許可を出力する'], world: true }
        ] }
];
